### ISSUE TITLE
Layers that are not data, or no desire to expose data

### ISSUE THREAD

**Issue by aaime** [opengeospatial/OGC-API-Maps#18]
E.g., decoration layers (grids, map borders, watermarks of sort), maps cascaded from other maps and tiles servers (yes, cascading is pretty much alive).

**Comment by aaime** [comment]
Also quite common and important, the stand alone WMS/WMTS case, where the only desire is to provide access to the rendered maps without giving access to the data (which might include turning off feature info too, the operation should be optional).

**Comment by pomakis** [comment]
It's technically possible to do this by having the /collections/{collectionId} endpoint return "404 Not Found" or "401 Unauthorized" (and an appropriate OPTIONS response), while having /collections/{collectionId}/map still respond to layer requests.  However, this by itself wouldn't be workable in practice, because there'd be no way for a client to know what list of available layers to present to the user without making an HTTP OPTIONS request to every collection endpoint to see which ones can serve layers.  A similar issue would exist when attempting to request a layer consisting of multiple collections.  I think it's essential for the /collections endpoint to somehow indicate the capabilities of each collection.

**Comment by joanma747** [comment]
Each collection that is exposed as a map of as a tile needs to expose a link to this map o tile in the collections/collection/id with the rel "map" or "tiles", exposing the CRS and the TileMatrixSet supported.
